#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

commit_msg_file=$1
commit_msg=$(cat "$commit_msg_file")

# Regex Conventional Commit
pattern="^(feat|fix|docs|style|refactor|test|chore)(\(.+\))?: .+"

if ! echo "$commit_msg" | grep -Eq "$pattern"; then
  echo ""
  echo "❌ Invalid commit message!"
  echo ""
  echo "👉 Use Conventional Commit format:"
  echo "   feat: add login api"
  echo "   fix: bug fix"
  echo "   docs: update readme"
  echo ""
  exit 1
fi

echo "✅ Commit message valid"dotnet husky run
